version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000 && python manage.py migrate"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
    ports:
      - "8000:8000"
  

  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - "6379"
    volumes: 
      - cache:/data
    networks:
      - web-network

volumes:
  birthdaymail:
  cache:

networks:
  web-network:
    driver: bridge