version: '3.8'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  # web_migrate:
  #   extends:
  #     service: web
  #   command: python manage.py migrate
  

  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - "6379"
    volumes: 
      - cache:/data
    networks:
      - web-network

volumes:
  birthdaymail:
  cache:

networks:
  web-network:
    driver: bridge