# Generated by Django 5.0.4 on 2024-04-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=60)),
                ("dob", models.DateField()),
                ("phonenumber", models.IntegerField()),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
